# Generated by Django 5.1.4 on 2024-12-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("rollno", models.IntegerField()),
                ("marks", models.IntegerField()),
                ("gf", models.CharField(max_length=64)),
                ("bf", models.CharField(max_length=64)),
            ],
        ),
    ]
