# Generated by Django 5.1.3 on 2024-11-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eno", models.IntegerField()),
                ("ename", models.CharField(max_length=20)),
                ("esal", models.FloatField()),
                ("eaddr", models.CharField(max_length=30)),
            ],
        ),
    ]
